### ISSUE TITLE
Error running Iris example in yarn-client mode

### ISSUE THREAD

**Issue by Shotgunosine** [deeplearning4j/dl4j-spark-cdh5-examples#13]
I am trying to modify the spark iris example to work in yarn-client mode, but I'm getting an error.

Here is the example I'm working on:
https://github.com/deeplearning4j/dl4j-spark-cdh5-examples/blob/master/src/main/java/org/deeplearning4j/examples/mlp/IrisLocal.java

I commented out line 33 from that example so that set master is not being set. Then I ran it with the following command:
`spark-shell --master yarn --deploy-mode client --class org.deeplearning4j.examples.mlp.IrisLocal --jars /tmp/dl4j-spark-cdh5-examples/target/dl4j-spark-cdh5-examples-1.0-SNAPSHOT-bin.jar /tmp/dl4j-spark-cdh5-examples/target/dl4j-spark-cdh5-examples-1.0-SNAPSHOT-bin.jar`

The job starts, but errors out with the message:
`java.io.FileNotFoundException: File file:/tmp/canova_temp3479665195216506528file does not exist
`I have confirmed that it will run when started with the following command:
`spark-shell --master local --class org.deeplearning4j.examples.mlp.IrisLocal --jars /tmp/dl4j-spark-cdh5-examples/target/dl4j-spark-cdh5-examples-1.0-SNAPSHOT-bin.jar /tmp/dl4j-spark-cdh5-examples/target/dl4j-spark-cdh5-examples-1.0-SNAPSHOT-bin.jar
`
Are there more changes I need to make to that example to be able to run it in yarn-client mode?

In case it matters:
OS: RHEL 6.6
Java: 1.7.0_67
Maven: 3.2.3

**Comment by Shotgunosine** [comment]
Here is the Java source that I used:

```
package org.deeplearning4j.examples.mlp;
 
import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaSparkContext;
import org.canova.api.records.reader.RecordReader;
import org.canova.api.records.reader.impl.CSVRecordReader;
import org.canova.api.util.ClassPathResource;
import org.deeplearning4j.nn.api.OptimizationAlgorithm;
import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.layers.DenseLayer;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer;
import org.nd4j.linalg.lossfunctions.LossFunctions;
 
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
 
/** Very simple example running Iris on Spark (local) using local data input */
public class IrisLocal {
 
    public static void main(String[] args) throws Exception {
 
        //Set up data. CSVRecordReader converts CSV data into usable format
        ClassPathResource classPathResource = new ClassPathResource("iris_shuffled_normalized_csv.txt");
        String localDataPath = "file://" + classPathResource.getFile().getAbsolutePath();
        RecordReader recordReader = new CSVRecordReader(0,",");
        SparkConf sparkConf = new SparkConf();
        //sparkConf.setMaster("local[*]");
        sparkConf.setAppName("Iris");
 
        JavaSparkContext sc = new JavaSparkContext(sparkConf);
 
 
        //Create and initialize multi-layer network
        final int numInputs = 4;
        int outputNum = 3;
        int iterations = 1;
 
        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .seed(12345)
                .iterations(iterations)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .learningRate(1e-1)
                .l1(0.01).regularization(true).l2(1e-3)
                .list(3)
                .layer(0, new DenseLayer.Builder().nIn(numInputs).nOut(3)
                        .activation("tanh")
                        .weightInit(WeightInit.XAVIER)
                        .build())
                .layer(1, new DenseLayer.Builder().nIn(3).nOut(2)
                        .activation("tanh")
                        .weightInit(WeightInit.XAVIER)
                        .build())
                .layer(2, new OutputLayer.Builder(LossFunctions.LossFunction.MCXENT)
                        .weightInit(WeightInit.XAVIER)
                        .activation("softmax")
                        .nIn(2).nOut(outputNum).build())
                .backprop(true).pretrain(false)
                .build();
 
        MultiLayerNetwork net = new MultiLayerNetwork(conf);
        net.init();
        net.setUpdater(null);   //Workaround for a minor bug in 0.4-rc3.8
 
        //Create Spark network
        SparkDl4jMultiLayer sparkNetwork = new SparkDl4jMultiLayer(sc,net);
 
        int nEpochs = 6;
        List<float[]> temp = new ArrayList<>();
        for( int i=0; i<nEpochs; i++ ){
            MultiLayerNetwork network = sparkNetwork.fit(localDataPath, 4, recordReader);
            temp.add(network.params().data().asFloat().clone());
        }
 
        System.out.println("Parameters vs. iteration: ");
        for( int i=0; i<temp.size(); i++ ){
            System.out.println(i + "\t " + Arrays.toString(temp.get(i)));
        }
    }
 
}
```

**Comment by Shotgunosine** [comment]
I've done a little bit more digging and I think I've been able to narrow down the section of SparkDl4jMultilayer.java (from version 0.4rc3.8) that is causing the issue, but I don't know how to resolve it. I've copied the relevant section of the code, and logs supporting the location of the error. Can anyone give me any guidance about how I can resolve this issue?

Comparing the messages produced between a successful local run and a failed yarn-client run, I think the issue is when runIteration is trying to run the gradient adder method with foreach.

Here's the runIteration class with the relevant log messages bolded:

private void runIteration(JavaRDD<DataSet> rdd) {
 
        log.info("Broadcasting initial parameters of length " + network.numParams(false));
        INDArray valToBroadcast = network.params(false);
        this.params = sc.broadcast(valToBroadcast);
        Updater updater = network.getUpdater();
        if(updater == null) {
            network.setUpdater(UpdaterCreator.getUpdater(network));
            log.warn("Unable to propagate null updater");
            updater = network.getUpdater();
        }
        this.updater = sc.broadcast(updater);
 
 
        int paramsLength = network.numParams(false);
        boolean accumGrad = sc.getConf().getBoolean(ACCUM_GRADIENT, false);
 
 
        if(accumGrad) {
            //Learning via averaging gradients
            JavaRDD<Tuple2<Gradient,Updater>> results = rdd.mapPartitions(new GradientAccumFlatMap(conf.toJson(), this.params, this.updater),true).cache();
            log.info("Ran iterative reduce...averaging results now.");
 
            JavaRDD<Gradient> resultsGradient = results.map(new GradientFromTupleFunction());
 
            GradientAdder a = new GradientAdder(paramsLength);
            resultsGradient.foreach(a);
            INDArray accumulatedGradient = a.getAccumulator().value();
            boolean divideGrad = sc.getConf().getBoolean(DIVIDE_ACCUM_GRADIENT,false);
            if(divideGrad)
                accumulatedGradient.divi(results.partitions().size());
            log.info("Accumulated parameters");
            log.info("Summed gradients.");
            network.setParameters(network.params(false).addi(accumulatedGradient));
            log.info("Set parameters");
 
            log.info("Processing updaters");
            JavaRDD<Updater> resultsUpdater = results.map(new UpdaterFromGradientTupleFunction());
 
            UpdaterAggregator aggregator = resultsUpdater.aggregate(
                    resultsUpdater.first().getAggregator(false),
                    new UpdaterElementCombiner(),
                    new UpdaterAggregatorCombiner()
            );
            Updater combinedUpdater = aggregator.getUpdater();
            network.setUpdater(combinedUpdater);
            log.info("Set updater");
        }
        else {
            //Standard parameter averaging
            JavaRDD<Tuple3<INDArray,Updater,Double>> results = rdd.mapPartitions(new IterativeReduceFlatMap(conf.toJson(),
                    this.params, this.updater, this.bestScoreAcc),true).cache();
 
            JavaRDD<INDArray> resultsParams = results.map(new INDArrayFromTupleFunction());
            **log.info("Ran iterative reduce... averaging parameters now.");**
            Adder a = new Adder(paramsLength);
            resultsParams.foreach(a);
            INDArray newParams = a.getAccumulator().value();
            **log.info("Accumulated parameters");**
            newParams.divi(rdd.partitions().size());
            log.info("Divided by partitions");
            network.setParameters(newParams);
            log.info("Set parameters");
 
            log.info("Processing updaters");
            JavaRDD<Updater> resultsUpdater = results.map(new UpdaterFromTupleFunction());
 
            JavaDoubleRDD scores = results.mapToDouble(new DoubleFunction<Tuple3<INDArray,Updater,Double>>(){
                @Override
                public double call(Tuple3<INDArray, Updater, Double> t3) throws Exception {
                    return t3._3();
                }
            });
            lastScore = scores.mean();
 
            Updater resultsUpdaterFirst = resultsUpdater.first();
            if(resultsUpdaterFirst != null) {
                UpdaterAggregator aggregator = resultsUpdater.aggregate(
                        resultsUpdaterFirst.getAggregator(false),
                        new UpdaterElementCombiner(),
                        new UpdaterAggregatorCombiner()
                );
                Updater combinedUpdater = aggregator.getUpdater();
                network.setUpdater(combinedUpdater);
                log.info("Set updater");
            }
            else {
                throw new IllegalStateException("No updater to combine");
            }
 
        }
    }

The yarn-client mode run prints the "Broadcasting initial parameters" message and the "Ran iterative reduce", but dies before it gets to "Accumulated Parameters."

**16/04/15 09:04:04 INFO SparkDl4jMultiLayer: Broadcasting initial parameters of length 32**
16/04/15 09:04:04 INFO MemoryStore: ensureFreeSpace(648) called with curMem=344195, maxMem=278302556
16/04/15 09:04:04 INFO MemoryStore: Block broadcast_2 stored as values in memory (estimated size 648.0 B, free 265.1 MB)
16/04/15 09:04:04 INFO MemoryStore: ensureFreeSpace(1186) called with curMem=344843, maxMem=278302556
16/04/15 09:04:04 INFO MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 1186.0 B, free 265.1 MB)
16/04/15 09:04:04 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on edge001.domain.net:42206 (size: 1186.0 B, free: 265.4 MB)
16/04/15 09:04:04 INFO BlockManagerMaster: Updated info of block broadcast_2_piece0
16/04/15 09:04:04 INFO SparkContext: Created broadcast 2 from broadcast at SparkDl4jMultiLayer.java:299
16/04/15 09:04:04 INFO MemoryStore: ensureFreeSpace(304) called with curMem=346029, maxMem=278302556
16/04/15 09:04:04 INFO MemoryStore: Block broadcast_3 stored as values in memory (estimated size 304.0 B, free 265.1 MB)
16/04/15 09:04:04 INFO MemoryStore: ensureFreeSpace(335) called with curMem=346333, maxMem=278302556
16/04/15 09:04:04 INFO MemoryStore: Block broadcast_3_piece0 stored as bytes in memory (estimated size 335.0 B, free 265.1 MB)
16/04/15 09:04:04 INFO BlockManagerInfo: Added broadcast_3_piece0 in memory on edge001.domain.net:42206 (size: 335.0 B, free: 265.4 MB)
16/04/15 09:04:04 INFO BlockManagerMaster: Updated info of block broadcast_3_piece0
16/04/15 09:04:04 INFO SparkContext: Created broadcast 3 from broadcast at SparkDl4jMultiLayer.java:306
**16/04/15 09:04:04 INFO SparkDl4jMultiLayer: Ran iterative reduce... averaging parameters now.**
16/04/15 09:04:04 INFO SparkContext: Starting job: foreach at SparkDl4jMultiLayer.java:351
16/04/15 09:04:04 INFO DAGScheduler: Got job 0 (foreach at SparkDl4jMultiLayer.java:351) with 2 output partitions (allowLocal=false)
16/04/15 09:04:04 INFO DAGScheduler: Final stage: Stage 0(foreach at SparkDl4jMultiLayer.java:351)
16/04/15 09:04:04 INFO DAGScheduler: Parents of final stage: List()
16/04/15 09:04:04 INFO DAGScheduler: Missing parents: List()
16/04/15 09:04:04 INFO DAGScheduler: Submitting Stage 0 (MapPartitionsRDD[4] at map at SparkDl4jMultiLayer.java:348), which has no missing parents
16/04/15 09:04:04 INFO MemoryStore: ensureFreeSpace(10648) called with curMem=346668, maxMem=278302556
16/04/15 09:04:04 INFO MemoryStore: Block broadcast_4 stored as values in memory (estimated size 10.4 KB, free 265.1 MB)
16/04/15 09:04:04 INFO MemoryStore: ensureFreeSpace(7188) called with curMem=357316, maxMem=278302556
16/04/15 09:04:04 INFO MemoryStore: Block broadcast_4_piece0 stored as bytes in memory (estimated size 7.0 KB, free 265.1 MB)
16/04/15 09:04:04 INFO BlockManagerInfo: Added broadcast_4_piece0 in memory on edge001.domain.net:42206 (size: 7.0 KB, free: 265.4 MB)
16/04/15 09:04:04 INFO BlockManagerMaster: Updated info of block broadcast_4_piece0
16/04/15 09:04:04 INFO SparkContext: Created broadcast 4 from broadcast at DAGScheduler.scala:839
16/04/15 09:04:04 INFO DAGScheduler: Submitting 2 missing tasks from Stage 0 (MapPartitionsRDD[4] at map at SparkDl4jMultiLayer.java:348)
16/04/15 09:04:04 INFO YarnScheduler: Adding task set 0.0 with 2 tasks
16/04/15 09:04:04 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, worker001.domain.net, PROCESS_LOCAL, 1395 bytes)
16/04/15 09:04:04 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1, worker002.domain.net, PROCESS_LOCAL, 1395 bytes)
16/04/15 09:04:05 INFO BlockManagerInfo: Added broadcast_4_piece0 in memory on worker001.domain.net:35440 (size: 7.0 KB, free: 530.3 MB)
16/04/15 09:04:05 INFO BlockManagerInfo: Added broadcast_4_piece0 in memory on worker002.domain.net:39564 (size: 7.0 KB, free: 530.3 MB)
16/04/15 09:04:06 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on worker002.domain.net:39564 (size: 45.6 KB, free: 530.2 MB)
16/04/15 09:04:06 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on worker001.domain.net:35440 (size: 45.6 KB, free: 530.2 MB)
16/04/15 09:04:06 WARN TaskSetManager: Lost task 1.0 in stage 0.0 (TID 1, worker002.domain.net): java.io.FileNotFoundException: File file:/tmp/canova_temp1737687803052694404file does not exist
        at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:611)
        at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:824)
        at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:601)
        at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:421)
        at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.<init>(ChecksumFileSystem.java:140)
        at org.apache.hadoop.fs.ChecksumFileSystem.open(ChecksumFileSystem.java:341)
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:766)
        at org.apache.hadoop.mapred.LineRecordReader.<init>(LineRecordReader.java:108)
        at org.apache.hadoop.mapred.TextInputFormat.getRecordReader(TextInputFormat.java:67)
        at org.apache.spark.rdd.HadoopRDD$$anon$1.<init>(HadoopRDD.scala:236)
        at org.apache.spark.rdd.HadoopRDD.compute(HadoopRDD.scala:212)
        at org.apache.spark.rdd.HadoopRDD.compute(HadoopRDD.scala:101)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
        at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:70)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:242)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
        at org.apache.spark.scheduler.Task.run(Task.scala:64)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)


On the other hand, the successful local run dies does make it to the "Accumulated Parameters" message:

**16/04/15 09:02:55 INFO SparkDl4jMultiLayer: Broadcasting initial parameters of length 32**
16/04/15 09:02:55 INFO MemoryStore: ensureFreeSpace(648) called with curMem=344198, maxMem=278302556
16/04/15 09:02:55 INFO MemoryStore: Block broadcast_2 stored as values in memory (estimated size 648.0 B, free 265.1 MB)
16/04/15 09:02:55 INFO MemoryStore: ensureFreeSpace(1186) called with curMem=344846, maxMem=278302556
16/04/15 09:02:55 INFO MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 1186.0 B, free 265.1 MB)
16/04/15 09:02:55 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on localedge:52787 (size: 1186.0 B, free: 265.4 MB)
16/04/15 09:02:55 INFO BlockManagerMaster: Updated info of block broadcast_2_piece0
16/04/15 09:02:55 INFO SparkContext: Created broadcast 2 from broadcast at SparkDl4jMultiLayer.java:299
16/04/15 09:02:55 INFO MemoryStore: ensureFreeSpace(304) called with curMem=346032, maxMem=278302556
16/04/15 09:02:55 INFO MemoryStore: Block broadcast_3 stored as values in memory (estimated size 304.0 B, free 265.1 MB)
16/04/15 09:02:55 INFO MemoryStore: ensureFreeSpace(335) called with curMem=346336, maxMem=278302556
16/04/15 09:02:55 INFO MemoryStore: Block broadcast_3_piece0 stored as bytes in memory (estimated size 335.0 B, free 265.1 MB)
16/04/15 09:02:55 INFO BlockManagerInfo: Added broadcast_3_piece0 in memory on localedge:52787 (size: 335.0 B, free: 265.4 MB)
16/04/15 09:02:55 INFO BlockManagerMaster: Updated info of block broadcast_3_piece0
16/04/15 09:02:55 INFO SparkContext: Created broadcast 3 from broadcast at SparkDl4jMultiLayer.java:306
**16/04/15 09:02:55 INFO SparkDl4jMultiLayer: Ran iterative reduce... averaging parameters now.**
16/04/15 09:02:55 INFO SparkContext: Starting job: foreach at SparkDl4jMultiLayer.java:351
16/04/15 09:02:55 INFO DAGScheduler: Got job 0 (foreach at SparkDl4jMultiLayer.java:351) with 1 output partitions (allowLocal=false)
16/04/15 09:02:55 INFO DAGScheduler: Final stage: Stage 0(foreach at SparkDl4jMultiLayer.java:351)
16/04/15 09:02:55 INFO DAGScheduler: Parents of final stage: List()
16/04/15 09:02:55 INFO DAGScheduler: Missing parents: List()
16/04/15 09:02:55 INFO DAGScheduler: Submitting Stage 0 (MapPartitionsRDD[4] at map at SparkDl4jMultiLayer.java:348), which has no missing parents
16/04/15 09:02:55 INFO MemoryStore: ensureFreeSpace(10648) called with curMem=346671, maxMem=278302556
16/04/15 09:02:55 INFO MemoryStore: Block broadcast_4 stored as values in memory (estimated size 10.4 KB, free 265.1 MB)
16/04/15 09:02:55 INFO MemoryStore: ensureFreeSpace(7191) called with curMem=357319, maxMem=278302556
16/04/15 09:02:55 INFO MemoryStore: Block broadcast_4_piece0 stored as bytes in memory (estimated size 7.0 KB, free 265.1 MB)
16/04/15 09:02:55 INFO BlockManagerInfo: Added broadcast_4_piece0 in memory on localedge:52787 (size: 7.0 KB, free: 265.4 MB)
16/04/15 09:02:55 INFO BlockManagerMaster: Updated info of block broadcast_4_piece0
16/04/15 09:02:55 INFO SparkContext: Created broadcast 4 from broadcast at DAGScheduler.scala:839
16/04/15 09:02:55 INFO DAGScheduler: Submitting 1 missing tasks from Stage 0 (MapPartitionsRDD[4] at map at SparkDl4jMultiLayer.java:348)
16/04/15 09:02:55 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks
16/04/15 09:02:55 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, localedge, PROCESS_LOCAL, 1395 bytes)
16/04/15 09:02:55 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
16/04/15 09:02:55 INFO Executor: Fetching http://10.0.0.4:60510/jars/dl4j-spark-cdh5-examples-1.0-SNAPSHOT-bin.jar with timestamp 1460725372538
16/04/15 09:02:56 INFO Utils: Fetching http://10.0.0.4:60510/jars/dl4j-spark-cdh5-examples-1.0-SNAPSHOT-bin.jar to /tmp/spark-6d068936-d909-4b44-a22d-cc552f4502d7/userFiles-ed11e030-b644-4367-bab2-32d5d1578fd6/fetchFileTemp8166516003922387281.tmp
16/04/15 09:02:56 INFO Executor: Adding file:/tmp/spark-6d068936-d909-4b44-a22d-cc552f4502d7/userFiles-ed11e030-b644-4367-bab2-32d5d1578fd6/dl4j-spark-cdh5-examples-1.0-SNAPSHOT-bin.jar to class loader
16/04/15 09:02:56 INFO CacheManager: Partition rdd_3_0 not found, computing it
16/04/15 09:02:56 INFO HadoopRDD: Input split: file:/tmp/canova_temp5676315452510987619file:0+6679
16/04/15 09:02:56 INFO deprecation: mapred.tip.id is deprecated. Instead, use mapreduce.task.id
16/04/15 09:02:56 INFO deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
16/04/15 09:02:56 INFO deprecation: mapred.task.is.map is deprecated. Instead, use mapreduce.task.ismap
16/04/15 09:02:56 INFO deprecation: mapred.task.partition is deprecated. Instead, use mapreduce.task.partition
16/04/15 09:02:56 INFO deprecation: mapred.job.id is deprecated. Instead, use mapreduce.job.id
16/04/15 09:02:56 INFO BlockManager: Removing broadcast 0
16/04/15 09:02:56 INFO BlockManager: Removing block broadcast_0
16/04/15 09:02:56 INFO MemoryStore: Block broadcast_0 of size 304 dropped from memory (free 277938350)
16/04/15 09:02:56 INFO BlockManager: Removing block broadcast_0_piece0
16/04/15 09:02:56 INFO MemoryStore: Block broadcast_0_piece0 of size 335 dropped from memory (free 277938685)
16/04/15 09:02:56 INFO BlockManagerInfo: Removed broadcast_0_piece0 on localedge:52787 in memory (size: 335.0 B, free: 265.4 MB)
16/04/15 09:02:56 INFO BlockManagerMaster: Updated info of block broadcast_0_piece0
16/04/15 09:02:56 INFO ContextCleaner: Cleaned broadcast 0
16/04/15 09:02:56 WARN BaseOptimizer: Objective function automatically set to minimize. Set stepFunction in neural net configuration to change default settings.
16/04/15 09:02:56 INFO ScoreIterationListener: Score at iteration 0 is 1.1140285347404084
16/04/15 09:02:56 INFO MemoryStore: ensureFreeSpace(1824) called with curMem=363871, maxMem=278302556
16/04/15 09:02:56 INFO MemoryStore: Block rdd_3_0 stored as values in memory (estimated size 1824.0 B, free 265.1 MB)
16/04/15 09:02:56 INFO BlockManagerInfo: Added rdd_3_0 in memory on localedge:52787 (size: 1824.0 B, free: 265.4 MB)
16/04/15 09:02:56 INFO BlockManagerMaster: Updated info of block rdd_3_0
16/04/15 09:02:56 INFO Adder: Invoking add operation
16/04/15 09:02:56 INFO Adder: Invoked add operation
16/04/15 09:02:56 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 4098 bytes result sent to driver
16/04/15 09:02:56 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 1084 ms on localedge (1/1)
16/04/15 09:02:56 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
16/04/15 09:02:56 INFO DAGScheduler: Stage 0 (foreach at SparkDl4jMultiLayer.java:351) finished in 1.116 s
16/04/15 09:02:57 INFO DAGScheduler: Job 0 finished: foreach at SparkDl4jMultiLayer.java:351, took 1.242184 s
**16/04/15 09:02:57 INFO SparkDl4jMultiLayer: Accumulated parameters**
16/04/15 09:02:57 INFO SparkDl4jMultiLayer: Divided by partitions
16/04/15 09:02:57 INFO SparkDl4jMultiLayer: Set parameters
16/04/15 09:02:57 INFO SparkDl4jMultiLayer: Processing updaters

**Comment by Shotgunosine** [comment]
Here are the full logs for the yarn run where things break and the local run where things work.

[yarn_full_log.txt](https://github.com/deeplearning4j/dl4j-spark-cdh5-examples/files/231810/yarn_full_log.txt)
[local_full_log.txt](https://github.com/deeplearning4j/dl4j-spark-cdh5-examples/files/231811/local_full_log.txt)

I also made a few small changes to irislocal.java, trying to debug this myself. Here is the version I've been using.

```
package org.deeplearning4j.examples.mlp;

import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaSparkContext;
import org.canova.api.records.reader.RecordReader;
import org.canova.api.records.reader.impl.CSVRecordReader;
import org.canova.api.util.ClassPathResource;
import org.deeplearning4j.nn.api.OptimizationAlgorithm;
import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.layers.DenseLayer;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer;
import org.nd4j.linalg.lossfunctions.LossFunctions;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/** Very simple example running Iris on Spark (local) using local data input */
public class IrisLocal {

    public static void main(String[] args) throws Exception {


        //Set up data. CSVRecordReader converts CSV data into usable format
        ClassPathResource classPathResource = new ClassPathResource("iris_shuffled_normalized_csv.txt");
        String localDataPath = "file://" + classPathResource.getFile().getAbsolutePath();
        RecordReader recordReader = new CSVRecordReader(0,",");
        SparkConf sparkConf = new SparkConf();
        //sparkConf.setMaster("local[*]");
        sparkConf.setAppName("Iris");

        JavaSparkContext sc = new JavaSparkContext(sparkConf);


        //Create and initialize multi-layer network
        final int numInputs = 4;
        int outputNum = 3;
        int iterations = 1;

        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .seed(12345)
                .iterations(iterations)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .learningRate(1e-1)
                .l1(0.01).regularization(true).l2(1e-3)
                .list(3)
                .layer(0, new DenseLayer.Builder().nIn(numInputs).nOut(3)
                        .activation("tanh")
                        .weightInit(WeightInit.XAVIER)
                        .build())
                .layer(1, new DenseLayer.Builder().nIn(3).nOut(2)
                        .activation("tanh")
                        .weightInit(WeightInit.XAVIER)
                        .build())
                .layer(2, new OutputLayer.Builder(LossFunctions.LossFunction.MCXENT)
                        .weightInit(WeightInit.XAVIER)
                        .activation("softmax")
                        .nIn(2).nOut(outputNum).build())
                .backprop(true).pretrain(false)
                .build();

        MultiLayerNetwork net = new MultiLayerNetwork(conf);
        net.init();
        net.setUpdater(null);   //Workaround for a minor bug in 0.4-rc3.8

        //Create Spark network
        SparkDl4jMultiLayer sparkNetwork = new SparkDl4jMultiLayer(sc,net);

        int nEpochs = 6;
        List<float[]> temp = new ArrayList<>();
        for( int i=0; i<nEpochs; i++ ){
            MultiLayerNetwork network = sparkNetwork.fit(localDataPath, 4, recordReader);
            temp.add(network.params().data().asFloat().clone());
        }
        System.out.println(sc.getConf().getBoolean(sparkNetwork.ACCUM_GRADIENT, false));

        System.out.println("Parameters vs. iteration: ");
        for( int i=0; i<temp.size(); i++ ){
            System.out.println(i + "\t " + Arrays.toString(temp.get(i)));
        }
    }

}

```

**Comment by AlexDBlack** [comment]
@Shotgunosine sorry I didn't get to this sooner
can you check out the branch "ab_iristest" and try running it again via yarn?
I suspect the problem here is that it's not possible to read the data (which is bundled into the jar file) from the jar using JavaSparkContext.textFile(). Hopefully I've fixed that in the new branch.

**Comment by Shotgunosine** [comment]
@AlexDBlack hmm, using that I get a file not found error even in local mode:

`java.io.FileNotFoundException: class path resource [iris_shuffled_normalized_csv.txt] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/tmp/dl4j-spark-cdh5-examples/target/dl4j-spark-cdh5-examples-1.0-SNAPSHOT-bin.jar!/iris_shuffled_normalized_csv.txt`

After googling, I found a different way to load the file that seems to work, using org.apache.commons.io.IOUtils:
`String irisDataContents = IOUtils.toString(classPathResource.getInputStream());
`
Instead of FileUtils with:
`String irisDataContents = FileUtils.readFileToString(classPathResource.getFile());`

With that change the example works for both local and yarn masters. You mentioned that the change is not good for loading large files, is there an example of how that should be done?

**Comment by AlexDBlack** [comment]
Ok, thanks. I'll switch to that version for the example.
It's a bad idea because we have to load the entire data set into memory on the driver. And more to the point it has to be on the classpath (likely in the jar itself), which is obviously bad for large files.
For larger files, the more sensible option is to use JavaSparkContext.textFile(String), where your data is in HDFS, then use RecordReaderFunction to map the JavaRDD<String> it to a JavaRDD<DataSet>

I'll close this and push up a version of the example using .getInputStream()
