### ISSUE TITLE
Can't set javacpp target platform when building for linux from mac

### ISSUE THREAD

**Issue by osipov** [deeplearning4j/dl4j-spark-cdh5-examples#20]
By default, the existing pom.xml assumes that javacpp package in the package jar should contain the native binaries for the same platform as the one where the jar is built and packaged. Using  <javacpp.platform>linux-x86_64</javacpp.platform> as one of the properties in pom.xml doesn't help change the native binaries. Is there an option to do cross-platform builds, e.g. build on a Mac and deploy to Linux?

**Comment by agibsonccc** [comment]
nd4j-native-platform nd4j-cuda-7.5-platform artifact ids

**Comment by osipov** [comment]
I tried that, per dependency and properties below. When building on Mac org.bytedeco.javacpp still packages macosx-x86_64. **Are you sure that building for Linux from Mac is supported?** Here's my [pom.xml](https://gist.github.com/osipov/f9b3fa1ef4c39ca5a43d22a4b5463d9e) 


            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-native-platform</artifactId>
                <version>0.4.0</version>
                <classifier>linux-x86_64</classifier>
            </dependency>

    <properties>
        <javacpp.platform>linux-x86_64</javacpp.platform>
        <nd4j.version>0.4.0</nd4j.version>
        <nd4j.backend>nd4j-native-platform</nd4j.backend>
    </properties>

**Comment by saudet** [comment]
Don't specify a classifier, just the following as per http://nd4j.org/getstarted.html :
```xml
 <dependency>
   <groupId>org.nd4j</groupId>
   <artifactId>nd4j-native-platform</artifactId>
   <version>${nd4j.version}</version>
 </dependency>
```
